### ISSUE TITLE
ios 9 not support and not in any device of ios

### ISSUE THREAD

**Issue by shivam5x** [sectore/phonegap3-ios-datepicker-plugin#28]
Hi ,
I am getting error swizzled_pluginInitialize whenever i clicked on that but working well in android
, so let me know the solution.

Thanks 
Shivam

**Comment by sectore** [comment]
Please note that this repository is not maintained anymore as described here https://github.com/sectore/phonegap3-ios-datepicker-plugin/blob/master/README.md
