### ISSUE TITLE
Regarding Phonegap datepicker is not working in ios

### ISSUE THREAD

**Issue by arunrajmb** [sectore/phonegap3-ios-datepicker-plugin#29]
I have taken build for an ios i have used phonegap datepicker but datepicker in not opening in my iphone 5s can any tell me whats the issue

**Comment by sectore** [comment]
@arunrajmb Please use another library instead, because this project is not maintained anymore as described here https://github.com/sectore/phonegap3-ios-datepicker-plugin/blob/master/README.md Thanks!

**Comment by arunrajmb** [comment]
@sectore ok but i used cordova date picker plugin for both android and ios but it is working well in android but its not working in my iphone 5s can you help me to solve this issue
